### ISSUE TITLE
Functional Menu

### ISSUE THREAD

**Issue by TheOptimisticFactory** [KoalaMoala/Feuer#1]
### Summary

Basic menu has been implemented as per 08f92aaa7d2035266b0fdcb973d77c5bccdb6728.
- See [this branch](https://github.com/KoalaMoala/Feuer/commits/FEATURE-01-Menu) for up to date version.
### TODO List
- [ ] Find better colors and overall styling
- [x] Fix issue when going back to the main menu `(shouldn't be a grey screen)`
- [x] Create new fragment for Settings screen
- [x] Create new fragment for High-Score screen

**Comment by TheOptimisticFactory** [comment]
- [X] Fix issue when going back to the main menu (shouldn't be a grey screen)

Fixed as per 696d3649ad07546185f17ff72ce9f11a3a2f1623
- [X] Create new fragment for Settings screen

Fixed as per baa4bb772a240ddba5817e2142749b7a5110f11a
- [X] Create new fragment for High-Score screen

Fixed as per cefdb55cea7d783427e17e14bb49a5bad074057c
